[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-L/Library/Developer/CommandLineTools/usr/lib/swift/macosx/",
    "-C", "link-arg=-L/usr/lib/swift/",
    "-C", "link-arg=-Wl,-rpath,/Library/Developer/CommandLineTools/usr/lib/swift-5.5/macosx/",
    "-C", "link-arg=-Wl,-rpath,/usr/lib/swift"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-L/Library/Developer/CommandLineTools/usr/lib/swift/macosx/",
    "-C", "link-arg=-L/usr/lib/swift/",
    "-C", "link-arg=-Wl,-rpath,/Library/Developer/CommandLineTools/usr/lib/swift-5.5/macosx/",
    "-C", "link-arg=-Wl,-rpath,/usr/lib/swift"
]
